version: '3.3'
services:
  backend:
    image: qa_hub_backend:latest
    container_name: "qa_hub_backend"
    restart: always
    build:
      context: .
    ports:
      - '8080:8080'
    env_file:
      - ../.config/.env
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - qa_hub_network
    volumes:
      - qa_hub_backend:/usr/src/app/qa_hub_backend
      - type: bind
        source: $ENV_ATTACHMENTS_DIR
        target: $ENV_ATTACHMENTS_DIR_HOST
        read_only: false
        bind:
          create_host_path: true

volumes:
  qa_hub_backend:

networks:
  qa_hub_network: